# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: subscription
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
